name: Send Reminder Notifications

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # This will run daily at midnight UTC

jobs:
  send-reminders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # You can update this to a newer version if needed

      - name: Install dependencies
        run: npm install

      - name: Send Reminders
        run: |
          node sendReminders.js # Make sure your function is exported correctly
